openapi: "3.0.0"
info:
  title: Influx API Service
  version: 0.1.0
servers:
  - url: /api/v2
paths:
  /signin:
    $ref: "./paths/signin.yml"
  /:
    get:
      operationId: GetRoutes
      summary: Map of all top level routes available
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      responses:
        default:
          description: All routes
          content:
            application/json:
              schema:
                $ref: "#/components/parameters/TraceSpan"
components:
  parameters:
    $ref: "./components/parameters/traceSpan.yml"
